# Automation Core Layer Imp
env=local
base.url=None
api.base.url=https://restful-booker.herokuapp.com

browser=chrome
headless=false

timeouts.seconds=20

# For Infrastructure Abstraction Layer Imp
remote.enabled=false
remote.url=http://localhost:4444/wd/hub   
#execution.target=local   
