# Automation Core Layer Imp
env=local
base.url=file:///C:/Users/F6CAF02/Documents/Me/auth-prototype/login.html

browser=firefox
headless=false

timeouts.seconds=10000000

# For Infrastructure Abstraction Layer Imp
remote.enabled=false
remote.url=http://localhost:4444/wd/hub   
# execution.target=local   # optional override
